### ISSUE TITLE
Revisar rutas en index.js

### ISSUE THREAD

**Issue by daniel-dona** [manumedinat/TFG#2]
dani@dani-HP-Z600-Workstation:~/TFG/salida$ node index.js 
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open '**./mappings.r2rml.json**'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.<anonymous> (/home/dani/TFG/R2RML/funciones_ttl.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)

**Comment by manumedinat** [comment]
Buenas,

He cambiado las rutas del fichero index.js (ahora se encuentra en la carpeta R2RML y así no se genera confusión), dicho fichero 'mapping.2rml.json' se encuentra en la carpeta R2RML.
