### ISSUE TITLE
Revisar paquetes en packages.json

### ISSUE THREAD

**Issue by daniel-dona** [manumedinat/TFG#3]
dani@dani-HP-Z600-Workstation:~/TFG/salida$ node index.js 
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '**array-move**'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/dani/TFG/salida/index.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by manumedinat** [comment]
Buenas,

He indicado la instalación del package en el readme con más detalle para que no salga este fallo.
